baseURL: "https://yutao-sun.github.io/"
languageCode: "en-us"
title: "Personal Website"
theme: hugo-profile
publishdir: "docs"

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:

    #Dropdown menu
    - identifier: dropdown
      title: Example dropdown menu
      name: Dropdown
      weight: 2
    - identifier: dropdown1
      title: example dropdown 1
      name: example 1
      url: /#
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: example dropdown 2
      name: example 2
      url: /#
      parent: dropdown
      weight: 2

params:
  title: "Home Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Yutao Sun."
    subtitle: "This is my ORIE 5270 Personal Website"
    content: ""
    image: /images/hero.svg
    button:
      enable: true
      name: "Resume"
      url: "#"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a software developer with a passion for software engineer. I have a background in mathematics, algorithms, and database. I am currently studying at Cornell University. 

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "Java"
        - "C"
        - "C++"
        - "Prolog"
        - "Matlab"

  # Experience
  experience:
    enable: true
    items:
      - job: "Position A"
        company: "Company A"
        date: "Jan 2022 - present"
        content: "I am currently working as a software engineer developer. I do A here."

      - job: "Position B"
        company: "Company B"
        date: "Sep 2020 - Dec 2021"
        content: "I am currently working as a software engineer developer. I do B here."

      - job: "Position C"
        company: "Company C"
        date: "Sep 2009 - Dec 2020"
        content: "I am currently working as a software engineer developer. I do C here."


  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Engineer in Computer Science"
        school:
          name: "Cornell University"
        date: "2021 - 2022"

      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Rensselaer Polytechnic Institute"
        date: "2018 - 2021"

  # Achievements
  achievements:
    enable: true
    items:
      - title: Achievement A
        content: Content of Achievement A
      - title: Achievement B
        content: Content of Achievement B
      - title: Achievement C
        content: Content of Achievement C
      - title: Achievement D
        content: Content of Achievement D
      - title: Achievement E
        content: Content of Achievement E


  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com